<a href="https://colab.research.google.com/github/cpajitha/ML_Notes/blob/main/lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Read a list of values and store it as a numpy array

In [ ]:
import numpy as np
arr=[]
print("Enter a list of values:")
arr=input().split()
arr=np.array(arr)
print(arr)

Enter a list of values:
1 2 3
['1' '2' '3']


In [ ]:
import numpy as np
arr=[]
print("Enter a list of values:")
arr=input().split()
arr=np.array(arr)
print(arr)

Enter a list of values:
1 hi 2
['1' 'hi' '2']


In [ ]:
import numpy as np
arr=[]
print("Enter a list of values:")
arr=list(map(int,input().split()))
arr=np.array(arr)
print(arr)

Enter a list of values:
1 2 3 4
[1 2 3 4]


Read a matrix as a numpy array and find its transpose

In [ ]:
import numpy as np
rows=int(input("Enter the number of rows:"))
cols=int(input("Enter the number of columns:"))
print("Enter the elements of the matrix row-wise")
matrix=[]
for i  in range(rows):
  rows=list(map(int,input().split()))
  matrix.append(rows)
matrix=np.array(matrix)
mat_trans=np.transpose(matrix)
print("Transpose matrix:")
print(mat_trans)


Enter the number of rows:2
Enter the number of columns:3
Enter the elements of the matrix row-wise
1 2 3
4 5 6
Transpose matrix:
[[1 4]
 [2 5]
 [3 6]]


Read two matrics one 3x4 and other 4x3 and return the inner product

In [ ]:
import numpy as np
print("Enter the elements of 3x4 matrix row-wise")
mat1=[]
for i in range(3):
  rows=list(map(int,input().split()))
  mat1.append(rows)
mat1=np.array(mat1)

print("Enter the elements of 4x3 matrix row-wise")
mat2=[]
for i in range(4):
  rows=list(map(int,input().split()))
  mat2.append(rows)
mat2=np.array(mat2)

product=np.dot(mat1,mat2)
print("Inner product:")
print(product)

Enter the elements of 3x4 matrix row-wise
1 2 3 4
5 6 7 8
9 0 1 2
Enter the elements of 4x3 matrix row-wise
4 5 7
1 2 3
4 5 0
9 6 4
Inner product:
[[ 54  48  29]
 [126 120  85]
 [ 58  62  71]]


4)Define a class MatrixDotProduct,implement a method to perform xtranspose * y.Define a main and pass the matrices x and y and compute x transpose * y

In [ ]:
import numpy as np
class MatrixDotProduct:
  def __init__(self,X,Y):
    self.X=X
    self.Y=Y
  def transpose_dot_product(self):
    self.X=np.transpose(self.X)
    prod=np.dot(self.X,self.Y)
    return prod
def main():
  x=np.array([[1,2,3],[5,8,9]])
  y=np.array([[7,8,9],[10,11,12]])
  obj=MatrixDotProduct(x,y)
  prod=obj.transpose_dot_product()
  print(prod)
if __name__=="__main__":
  main()


[[ 57  63  69]
 [ 94 104 114]
 [111 123 135]]


Read a matrix
1)add all elements
2)add elements row-wise and return a column
3)add elements col-wise and return a row

In [ ]:
import numpy as np
rows=int(input("Enter the number of rows:"))
cols=int(input("Enter the number of columns"))
print("Enter the elements of matrix row-wise:")
mat=[]
for i in range(rows):
  rows=list(map(int,input().split())),
  mat.append(rows)
mat=np.array(mat)
print("1)sum:")
sum=np.sum(mat)
print(sum)
print("2)sum of elements row-wise")
sum=np.sum(mat,axis=1)
print(sum)
print("3)sum of elements column-wise:")
sum=np.sum(mat,axis=0)
print(sum)

Enter the number of rows:2
Enter the number of columns2
Enter the elements of matrix row-wise:
1 2
3 4
1)sum:
10
2)sum of elements row-wise
[3 7]
3)sum of elements column-wise:
[4 6]


Read two vectors and find the similarity using
1)Euclidean distance
2)cosine similarity


In [ ]:
import numpy as np
def euclid_dist(a,b):
  return np.linalg.norm(a-b)
def cosine_sim(a,b):
  dot_pdt=np.dot(a,b)
  norm_a=np.linalg.norm(a)
  norm_b=np.linalg.norm(b)
  cos_sim=dot_pdt/np.dot(norm_a,norm_b)
  return cos_sim

def main():
  a=list(map(int,input("Enter the elements of first vector:").split()))
  b=list(map(int,input("Enter the elements of second vector:").split()))
  a=np.array(a)
  b=np.array(b)
  euclidean_distance=euclid_dist(a,b)
  cosine_similarity=cosine_sim(a,b)
  print("Euclidean distance:",euclidean_distance)
  print("Cosine similarity:",cosine_similarity)

if __name__=="__main__":
  main()

Enter the elements of first vector:1 2
Enter the elements of second vector:3 4
Euclidean distance: 2.8284271247461903
Cosine similarity: 0.9838699100999074


Familiarization of pandas

In [ ]:
import pandas as pd
df=pd.read_csv("/content/data.csv")
df

Roll no        Name Class       Place
0        1  Ajitha C P    S1    Palakkad
1        2    Anjana P    S1    Palakkad
2        3     Amritha    S2  Malappuram
3        4     Aswathy    S3     Wayanad
4        5        Manu    S7      Kollam
5        6       Risha    S8      Kannur
6        7    Athithia    S7    Kasargod
7        8      Anagha    S7      Kannur
8        9     Akhitha    S7  Trivandrum
9       10        Amal    S6   Alappuzha

In [ ]:
df.head()

Roll no        Name Class       Place
0        1  Ajitha C P    S1    Palakkad
1        2    Anjana P    S1    Palakkad
2        3     Amritha    S2  Malappuram
3        4     Aswathy    S3     Wayanad
4        5        Manu    S7      Kollam

In [ ]:
df.tail()

Roll no      Name Class       Place
5        6     Risha    S8      Kannur
6        7  Athithia    S7    Kasargod
7        8    Anagha    S7      Kannur
8        9   Akhitha    S7  Trivandrum
9       10      Amal    S6   Alappuzha

In [ ]:
df.describe()

Roll no
count  10.00000
mean    5.50000
std     3.02765
min     1.00000
25%     3.25000
50%     5.50000
75%     7.75000
max    10.00000

Download the dataset and extract the folders and assign the training and testing folders into df1 and df2


In [1]:
import tarfile
import os
tar_file_path="/content/drive/MyDrive/ML_LAB/ohsumed-first-20000-docs.tar.gz"
extracting_path="/content/drive/MyDrive/ML_LAB/extracted_data"
if not os.path.exists(extracting_path):
  os.makedirs(extracting_path)
with tarfile.open(tar_file_path,'r') as tar:
  tar.extractall(extracting_path)
print("Untarred successfully")

Untarred successfully


In [2]:
import pandas as pd
import os
import glob
train_folder="/content/drive/MyDrive/ML_LAB/extracted_data/ohsumed-first-20000-docs/training"
test_folder="/content/drive/MyDrive/ML_LAB/extracted_data/ohsumed-first-20000-docs/test"

def create_dfs(folder_path):
  dataframes=[]
  for root,dirs,files in os.walk(folder_path):
    for file in files:
      filename=os.path.join(root,file)
      with open(filename,'r') as f:
        row=f.read().split()
        df=pd.DataFrame([row])
        dataframes.append(df)
  if dataframes:
    return pd.concat(dataframes,ignore_index=True)
  else:
    return pd.DataFrame()

df1=create_dfs(train_folder)
df2=create_dfs(test_folder)
df1
df2

0                1             2                   3    \
0           Haemophilus       influenzae    meningitis                with   
1               Mucosal  intussusception            to               avoid   
2      Gastrointestinal         function           and           structure   
3          Epidemiology               in          bone                 and   
4                   The         diabetic         foot.                Soft   
...                 ...              ...           ...                 ...   
12728      Interruption               of  professional                 and   
12729            Effect               of    thiopental                  on   
12730          Recovery          profile         after  desflurane-nitrous   
12731     Postoperative       myocardial      ischemia                  in   
12732          Enhanced     mobilization            of       intracellular   

              4             5                   6             7    \
0       prolonged      hospital             course.             A   
1       ascending  cholangitis.                Many       methods   
2              in  HIV-positive           patients.            We   
3           joint    infection.                 The       studies   
4          tissue           and                bone    infection.   
...           ...           ...                 ...           ...   
12728        home      activity               after  laparoscopic   
12729  neurologic       outcome           following      coronary   
12730       oxide        versus  isoflurane-nitrous         oxide   
12731    patients    undergoing            coronary        artery   
12732        Ca2+       induced                  by     halothane   

                   8                   9    ...  586  587  588  589  590  591  \
0        retrospective          evaluation  ...  NaN  NaN  NaN  NaN  NaN  NaN   
1                 have                been  ...  NaN  NaN  NaN  NaN  NaN  NaN   
2             examined                  19  ...  NaN  NaN  NaN  NaN  NaN  NaN   
3                   of  community-acquired  ...  NaN  NaN  NaN  NaN  NaN  NaN   
4             Diabetic           patients,  ...  NaN  NaN  NaN  NaN  NaN  NaN   
...                ...                 ...  ...  ...  ...  ...  ...  ...  ...   
12728  cholecystectomy               among  ...  NaN  NaN  NaN  NaN  NaN  NaN   
12729           artery              bypass  ...  NaN  NaN  NaN  NaN  NaN  NaN   
12730               in        outpatients.  ...  NaN  NaN  NaN  NaN  NaN  NaN   
12731           bypass               graft  ...  NaN  NaN  NaN  NaN  NaN  NaN   
12732               in         hepatocytes  ...  NaN  NaN  NaN  NaN  NaN  NaN   

       592  593  594  595  
0      NaN  NaN  NaN  NaN  
1      NaN  NaN  NaN  NaN  
2      NaN  NaN  NaN  NaN  
3      NaN  NaN  NaN  NaN  
4      NaN  NaN  NaN  NaN  
...    ...  ...  ...  ...  
12728  NaN  NaN  NaN  NaN  
12729  NaN  NaN  NaN  NaN  
12730  NaN  NaN  NaN  NaN  
12731  NaN  NaN  NaN  NaN  
12732  NaN  NaN  NaN  NaN  

[12733 rows x 596 columns]

In [3]:
df1

0               1             2             3    \
0        Augmentation     mentoplasty         using     Mersilene   
1            Multiple    intracranial     mucoceles    associated   
2         Replacement              of            an        aortic   
3                 The           value            of        indium   
4             Febrile         infants          less          than   
...               ...             ...           ...           ...   
10428        Afferent          nipple         valve   malfunction   
10429  Extracorporeal           shock          wave   lithotripsy   
10430   Tamm-Horsfall  autoantibodies            in  interstitial   
10431         Results              of  contemporary       radical   
10432           Total         bladder   replacement         using   

                 4                  5          6              7    \
0              mesh.               Many  different      materials   
1               with  phaeohyphomycosis         of            the   
2              valve               cusp      after       neonatal   
3                111          leukocyte   scanning             in   
4              eight              weeks       old.     Predictors   
...              ...                ...        ...            ...   
10428         caused                 by  anchoring        collar:   
10429             in        combination       with  transurethral   
10430      cystitis.       Interstitial   cystitis       presents   
10431     cystectomy                for   invasive        bladder   
10432  detubularized            sigmoid     colon:      technique   

                 8           9    ...  568  569  570  571  572  573  574  575  \
0                are   available  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1          paranasal    sinuses.  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
2      endocarditis.      Septic  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3                the  evaluation  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
4                 of  infection.  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
...              ...         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
10428             an  unexpected  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
10429        surgery         for  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
10430              a  diagnostic  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
10431        cancer:           a  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
10432            and    results.  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

       576  577  
0      NaN  NaN  
1      NaN  NaN  
2      NaN  NaN  
3      NaN  NaN  
4      NaN  NaN  
...    ...  ...  
10428  NaN  NaN  
10429  NaN  NaN  
10430  NaN  NaN  
10431  NaN  NaN  
10432  NaN  NaN  

[10433 rows x 578 columns]

In [4]:
df2

0                1             2                   3    \
0           Haemophilus       influenzae    meningitis                with   
1               Mucosal  intussusception            to               avoid   
2      Gastrointestinal         function           and           structure   
3          Epidemiology               in          bone                 and   
4                   The         diabetic         foot.                Soft   
...                 ...              ...           ...                 ...   
12728      Interruption               of  professional                 and   
12729            Effect               of    thiopental                  on   
12730          Recovery          profile         after  desflurane-nitrous   
12731     Postoperative       myocardial      ischemia                  in   
12732          Enhanced     mobilization            of       intracellular   

              4             5                   6             7    \
0       prolonged      hospital             course.             A   
1       ascending  cholangitis.                Many       methods   
2              in  HIV-positive           patients.            We   
3           joint    infection.                 The       studies   
4          tissue           and                bone    infection.   
...           ...           ...                 ...           ...   
12728        home      activity               after  laparoscopic   
12729  neurologic       outcome           following      coronary   
12730       oxide        versus  isoflurane-nitrous         oxide   
12731    patients    undergoing            coronary        artery   
12732        Ca2+       induced                  by     halothane   

                   8                   9    ...  586  587  588  589  590  591  \
0        retrospective          evaluation  ...  NaN  NaN  NaN  NaN  NaN  NaN   
1                 have                been  ...  NaN  NaN  NaN  NaN  NaN  NaN   
2             examined                  19  ...  NaN  NaN  NaN  NaN  NaN  NaN   
3                   of  community-acquired  ...  NaN  NaN  NaN  NaN  NaN  NaN   
4             Diabetic           patients,  ...  NaN  NaN  NaN  NaN  NaN  NaN   
...                ...                 ...  ...  ...  ...  ...  ...  ...  ...   
12728  cholecystectomy               among  ...  NaN  NaN  NaN  NaN  NaN  NaN   
12729           artery              bypass  ...  NaN  NaN  NaN  NaN  NaN  NaN   
12730               in        outpatients.  ...  NaN  NaN  NaN  NaN  NaN  NaN   
12731           bypass               graft  ...  NaN  NaN  NaN  NaN  NaN  NaN   
12732               in         hepatocytes  ...  NaN  NaN  NaN  NaN  NaN  NaN   

       592  593  594  595  
0      NaN  NaN  NaN  NaN  
1      NaN  NaN  NaN  NaN  
2      NaN  NaN  NaN  NaN  
3      NaN  NaN  NaN  NaN  
4      NaN  NaN  NaN  NaN  
...    ...  ...  ...  ...  
12728  NaN  NaN  NaN  NaN  
12729  NaN  NaN  NaN  NaN  
12730  NaN  NaN  NaN  NaN  
12731  NaN  NaN  NaN  NaN  
12732  NaN  NaN  NaN  NaN  

[12733 rows x 596 columns]